### ISSUE TITLE
It doesn't build in Ubuntu 16.04

### ISSUE THREAD

**Issue by cibersheep** [czinn/homeworlds#1]
When try to build the project:
```bash
g++ -g -Wall -MMD -std=c++0x    -c -o game.o game.cc
game.cc: In member function ‘int Game::winner() const’:
game.cc:133:12: error: ‘find_if’ was not declared in this scope
           }) != s.ships.end()) {
            ^
```

Possible fix is to `#include <algorithm>` into game.cc

**Comment by cibersheep** [comment]
You have a pull request #2 that might solve this issue

**Comment by czinn** [comment]
Merged #2, let me know if that fixes your build.

**Comment by cibersheep** [comment]
Yes! Fixed. Thank you.
```
homeworlds$ make
g++ -g -Wall -MMD -std=c++0x    -c -o game.o game.cc
g++ -g -Wall -MMD -std=c++0x    -c -o negamax.o negamax.cc
g++ -g -Wall -MMD -std=c++0x    -c -o game_io.o game_io.cc
g++ -g -Wall -MMD -std=c++0x    -c -o main.o main.cc
g++ game.o negamax.o game_io.o main.o -o main -g -Wall -MMD -std=c++0x
```

**Comment by cibersheep** [comment]
Oh. I should have closed this :)
